services:
  fastapi-app:
    build:
      context: ./fastapi-service
      dockerfile: Dockerfile
    image: 'fastapi-image:latest'
    container_name: 'fastapi-container'
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./fastapi-service:/fastapi-app
    ports:
      - "${FASTAPI_HOST_PORT}:${FASTAPI_SERVER_PORT}"
    env_file:
      - .env
    networks:
      - docker-network-test
  
  springboot-app:
    build:
      context: ./springboot-service
      dockerfile: Dockerfile
    image: 'springboot-image:latest'
    container_name: 'springboot-container'
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./springboot-service:/springboot-app
    ports:
      - "${SPRINGBOOT_HOST_PORT}:${SPRINGBOOT_SERVER_PORT}"
    env_file:
      - .env
    networks:
      - docker-network-test

networks:
  docker-network-test:
    name: docker-network-test