# Use a lightweight JDK runtime as the base image
FROM openjdk:17-jdk-slim

# Set working directory inside the container
WORKDIR /springboot-app

# Run the application using the Gradle wrapper
ENTRYPOINT ["sh", "./entrypoint.sh"]